database:
  name: sqlite
  output: database
documents:
  comment: Small CC collection for demo
  input:
    encoding: utf8
    format: json
    lang: zho
    path: /home/shengyi/764/CLIR/cc-news-zho-1000.jsonl
  output: false
  process:
    normalize:
      lowercase: false
      report: false
    stem: false
    stopwords: lucene
    strict_check: true
    tokenize: jieba
index:
  name: lucene
  output: index
queries:
  output: processed_queries
  parse: false
  process:
    normalize:
      lowercase: false
      report: false
    stem: false
    stopwords: lucene
    strict_check: true
    tokenize: jieba
retrieve:
  b: 0.4
  fb_docs: 10
  fb_terms: 10
  input:
    index:
      path: index
  k1: 0.9
  log_explanations: false
  log_explanations_cutoff: 10
  mu: 1000
  name: bm25
  number: 5
  original_query_weight: 0.5
  output: retrieve
  parse: false
  psq: false
  rm3: false
  rm3_logging: false
run:
  name: query translation truecase
  path: runs/query-translation-truecase
  results: results.txt
  stage1:
    mode: streaming
    num_jobs: 1
    progress_interval: 10000
  stage2:
    mode: streaming
    num_jobs: 1
    progress_interval: 10
score:
  input:
    format: trec
    path: /home/shengyi/764/CLIR/zho.toy-dev.qrels.v1-0.txt
  metrics:
  - ndcg_prime
  - ndcg
  - map
  - recall_100
  - recall_1000
topics:
  fields: title
  input:
    encoding: utf8
    format: json
    lang: zho
    path: /home/shengyi/764/CLIR/dev.topics.v1-0.jsonl
    prefix: false
    source: human translation
    strip_non_digits: false
  output: false
